// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  contact: dynamic(() => import("./Contact")),
  content_list: dynamic(() => import("./ContentList")),
  free_trial: dynamic(() => import("./FreeTrial")),
  gallery: dynamic(() => import("./Gallery")),
  hero: dynamic(() => import("./Hero")),
  players: dynamic(() => import("./Players")),
  program: dynamic(() => import("./Program")),
  team: dynamic(() => import("./Team")),
  welcome: dynamic(() => import("./Welcome")),
};
